Repository Xcov19/android-mycovidconnect, pull requests merged in 2020-09, with the labels that each got.

#6 Create ktlinter.yml
  .github/ktlinter.yml
Labels: needs-review

#16 Update README.md
  README.md
Labels: needs-review

#20 Update ktlinter.yml
  .github/ktlinter.yml
Labels: enhancement, needs-review

#17 mock session manager
  app/src/main/java/com/ht117/yukute/sessionmanager/SessionManager.kt
  app/src/main/java/com/ht117/yukute/sessionmanager/SessionManagerInterface.kt
Labels: enhancement, needs-review

#18 [BE] Data Retrieval
  app/build.gradle.kts
  app/google-services.json
  build.gradle.kts
  buildSrc/src/main/kotlin/Deps.kt
  buildSrc/src/main/kotlin/Version.kt
Labels: work-in-porgress
